language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

# scripts to be run such as tests
  - echo "no tests"

script:
  - docker --version
  - docker build -t simple-node .

